### ISSUE TITLE
Integrate with pzprxs

### ISSUE THREAD

**Issue by x-sheep** [3892myamya/sdvx#4]
Hi!

I've made a fork of pzpr at https://pzprxs.vercel.app/ with support for several new types.

Example:
https://pzprxs.vercel.app/p?chainedb/5/5/1k.g3o3h3i

Can you add support for these URLs to your Solver/Generator when available?

**Comment by 3892myamya** [comment]
Hello x-sheep. Sorry for the late reply. (I didn't notice the issues ...)

Thank you for contacting us.
For "https://pzprxs.vercel.app/", the solver support for the following puzzles has been completed at this time.

・Dotchi Loop ドッチループ
・Ovotovata
・Chained Block チェンブロ
・Canal View (With Generator ペンパガチャ)
・Choco Banana チョコバナナ
・Voxas (With Generator ペンパガチャ)
・Rassi Silai
・Tren パーキング

We will continue to add compatible puzzles, so please be patient.
We are looking forward to hearing from you.
😄 👍

**Comment by x-sheep** [comment]
pzprxs has been merged into puzz.link, so this issue is no longer needed. Thanks for your work in supporting the new types 🎉
